" vim:fdm=marker
" ********************************************
" * Thiago Massariolli Sigrist's .vimrc file *
" ********************************************

"   (L) Thiago Massariolli Sigrist 2007-2014
"   ----------------------------------------

" ********************************************
" ********************************************


" Be iMproved!
set nocompatible


" Bootstrap Vundle {{{1
filetype off

" runtimepath for vundle
set rtp+=~/.vim/bundle/vundle/

" assume we don't have vundle
let s:has_vundle = 0

" assume we don't need to bootstrap vundle
let s:bootstrap_vundle = 0

" check if vundle is present
if isdirectory(glob("~/.vim/bundle/vundle"))
    let s:has_vundle = 1
endif   " <vundle is present>

" install vundle if not present
" inspired by http://gist.github.com/frasertweedale/8265874
" and by http://mg.pov.lt/vim/vimrc
" TODO: Windows?!?
if !s:has_vundle
    " install vundle iff git is present
    if filereadable(glob("`which git`"))
        set nomore
        silent !mkdir -p ~/.vim/bundle
        silent !git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
        redraw!
        let s:has_vundle = 1
        let s:bootstrap_vundle = 1
    endif   " <git is present>
endif   " !s:has_vundle

if s:has_vundle
    " start vundle
    call vundle#rc()

    " Vundle Plugins {{{1
    " vundle manages vundle {{{2
    Plugin 'gmarik/vundle'

    " My Plugins here:
    " Libraries {{{2
    Plugin 'mattn/webapi-vim'
    Plugin 'rizzatti/funcoo.vim'
    Plugin 'drmikehenry/vim-fixkey'

    " Colorschemes {{{2
    Plugin 'altercation/vim-colors-solarized'
    Plugin 'w0ng/vim-hybrid'
    Plugin 'zeis/vim-kolor'
    Plugin 'jonathanfilip/vim-lucius'
    Plugin 'morhetz/gruvbox'
    Plugin 'vim-scripts/summerfruit256.vim'

    " Motion {{{2
    Plugin 'Lokaltog/vim-easymotion'
    Plugin 'tpope/vim-unimpaired'

    " Search & Tags {{{2
    Plugin 'nelstrom/vim-visual-star-search'
    Plugin 'osyo-manga/vim-anzu'
    Plugin 'rking/ag.vim'
    Plugin 'majutsushi/tagbar'

    " Git / GitHub / VCS {{{2
    Plugin 'tpope/vim-fugitive'
    Plugin 'mhinz/vim-signify'
    Plugin 'gregsexton/gitv'
    Plugin 'mattn/gist-vim'
    Plugin 'jaxbot/github-issues.vim'

    " File Browsing {{{2
    Plugin 'scrooloose/nerdtree'
    Plugin 'kien/ctrlp.vim'

    " Appearance {{{2
    Plugin 'myusuf3/numbers.vim'
    Plugin 'kien/rainbow_parentheses.vim'
    Plugin 'bling/vim-airline'
    Plugin 'nathanaelkane/vim-indent-guides'
    Plugin 'mhinz/vim-startify'
    Plugin 'qstrahl/vim-matchmaker'
    Plugin 'jszakmeister/vim-togglecursor'

    " Completion & Snippets {{{2
    Plugin 'SirVer/ultisnips'
    Plugin 'honza/vim-snippets'
    Plugin 'Valloric/YouCompleteMe'
    Plugin 'Raimondi/delimitMate'

    " Editing Utilities {{{2
    Plugin 'scrooloose/nerdcommenter'
    Plugin 'mutewinter/swap-parameters'
    Plugin 'tpope/vim-abolish'
    Plugin 'tpope/vim-surround'
    Plugin 'sk1418/Join'
    Plugin 'godlygeek/tabular'
    Plugin 'gcmt/wildfire.vim'
    Plugin 'matze/vim-move'

    " Yank, Undo, History {{{2
    Plugin 'maxbrunsfeld/vim-yankstack'
    Plugin 'tpope/vim-repeat'
    Plugin 'mbbill/undotree'

    " Syntax & Checking {{{2
    Plugin 'scrooloose/syntastic'

    " Language: CSS & Friends {{{2
    Plugin 'groenewege/vim-less'
    Plugin 'wavded/vim-stylus'

    " Language: HTML & Friends {{{2
    Plugin 'tristen/vim-sparkup'
    Plugin 'digitaltoad/vim-jade'
    Plugin 'Valloric/MatchTagAlways'
    Plugin 'mustache/vim-mustache-handlebars'

    " Language: JavaScript & Friends {{{2
    Plugin 'pangloss/vim-javascript'
    Plugin 'marijnh/tern_for_vim'
    Plugin 'elzr/vim-json'
    Plugin 'tpope/vim-jdaddy'
    Plugin 'maksimr/vim-jsbeautify'
    Plugin 'kchmck/vim-coffee-script'
    Plugin 'gkz/vim-ls'
    Plugin '29decibel/vim-stringify'
    Plugin 'othree/javascript-libraries-syntax.vim'

    " Language: Markdown {{{2
    Plugin 'tpope/vim-markdown'

    " Language: Puppet {{{2
    Plugin 'rodjek/vim-puppet'

    " Language: Python {{{2
    Plugin 'klen/python-mode'

    " Misc Utilities {{{2
    Plugin 'milkypostman/vim-togglelist'
    Plugin 'benmills/vimux'
    Plugin 'rizzatti/dash.vim'
    Plugin 'kballenegger/vim-autoreadwatch'
    Plugin 'tpope/vim-speeddating'
    "Plugin 'tpope/vim-endwise' - is there a way to enable it only for certain
    "filetypes?
    Plugin 'editorconfig/editorconfig-vim'
    Plugin 'justinmk/vim-gtfo'
    Plugin 'sk1418/HowMuch'
    Plugin 'sjl/clam.vim'

    " Install plugins if bootstrapping {{{1
    " bootstrap vundle if we have to
    if s:bootstrap_vundle
        " install all plugins
        silent PluginInstall
        quit

        " compile YCM
        silent !(cd ~/.vim/bundle/YouCompleteMe; ./install.sh)
    endif   " s:bootstrap_vundle
endif   " s:has_vundle

" Colorscheme {{{1
let g:kolor_underlined=1
silent! colorscheme solarized

" Basic Settings {{{1
" Detects file type and enables language-specific indentation
" Syntax highlighting always on
syntax on
filetype plugin indent on

" statusline always visible
set laststatus=2
set noshowmode

" Automatic indentation on new line
set autoindent

" Expands tabs/indents to 4 characters
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Smart line breaking
set linebreak

" Backspace options
set backspace=indent,eol,start

" Fold when markers are present
set foldmethod=marker

" Search highlighting and smartcase options
set hlsearch
set incsearch
set ignorecase
set smartcase

" Enable line numbers.
set number

" Enable current-line highlighting
set cursorline

" Wildmenu FTW
set wildmenu

" Virtual edit for visual blocks.
set virtualedit=block

" Terminal Settings {{{1
set ttimeoutlen=10

" Key Bindings {{{1
map <F10> :qa<return>

" C Syntax {{{1
" Use C syntax for .w files
let g:filetype_w = 'c'

" C-style indentation
autocmd FileType c,h,cpp,hpp,w set cindent

" C-style indentation options
" Non-default options here are:
"   - l1: align with a case label instead of the statement after it in the
"         same line. This is to have case blocks have the same indent whether
"         they have curly braces or not.
"   - (0: always have alignment match first non-white character in unopened
"         parentheses.
"   - U1: do the parens indenting even if the unopened parens is the last
"         character in its line.
"   - t0: indent a function return type declaration 0 chars from the margin.
set cinoptions=l1(0U1t0

" Automatic formatting of comments in C
" Non-default options here are:
"   - a: does automatic formatting of comment paragraphs.
"   - 1: prefers to line wrap before 1-letter words.
autocmd FileType c,h,cpp,hpp,w set formatoptions=acroql1

" Plugin Configurations {{{1
if s:has_vundle
    " bling/vim-airline {{{2
    set encoding=utf-8
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_powerline_fonts=1

    " kien/ctrlp.vim {{{2
    " runtimepath for CtrlP
    set runtimepath^=~/.vim/bundle/ctrlp.vim

    " open CtrlP in mixed mode by default
    let g:ctrlp_cmd = 'CtrlPMixed'

    " scrooloose/nerdtree {{{2
    " Mapping for NERDTree
    nnoremap <Leader>n :NERDTreeToggle<CR>

    " mbbill/undotree {{{2
    " Mapping for undotree
    nnoremap <F5> :UndotreeToggle<CR>

    " godlygeek/tabular {{{2
    " Tabularize mappings.
    if exists(":Tabularize")
        nmap <Leader>a= :Tabularize /=<CR>
        vmap <Leader>a= :Tabularize /=<CR>
        nmap <Leader>a: :Tabularize /:\zs<CR>
        vmap <Leader>a: :Tabularize /:\zs<CR>
    endif   " exists(":Tabularize")

    " SirVer/ultisnips {{{2
    " UltiSnips config to avoid conflict with YouCompleteMe.
    let g:UltiSnipsExpandTrigger = "<C-j>"

    " mhinz/vim-startify {{{2
    " vim-startify custom header
    let g:startify_custom_header = [
    \ "        ________ ++     ________",
    \ "       /VVVVVVVV\\++++  /VVVVVVVV\\",
    \ "       \\VVVVVVVV/++++++\\VVVVVVVV/",
    \ "        |VVVVVV|++++++++/VVVVV/'",
    \ "        |VVVVVV|++++++/VVVVV/'",
    \ "       +|VVVVVV|++++/VVVVV/'+",
    \ "     +++|VVVVVV|++/VVVVV/'+++++",
    \ "   +++++|VVVVVV|/VVVVV/'+++++++++",
    \ "     +++|VVVVVVVVVVV/'+++++++++",
    \ "       +|VVVVVVVVV/'+++++++++",
    \ "        |VVVVVVV/'+++++++++",
    \ "        |VVVVV/'+++++++++",
    \ "        |VVV/'+++++++++",
    \ "        'V/'   ++++++",
    \ "                 ++",
    \ "",
    \ ]

    " klen/python-mode {{{2
    let g:pymode_rope = 0
    let g:pymode_lint = 0
    let g:pymode_lint_write = 0
    let g:pymode_virtualenv = 1
    let g:pymode_syntax = 1
    let g:pymode_syntax_all = 1

    " Valloric/YouCompleteMe {{{2
    " Close preview window when done inserting.
    let g:ycm_add_preview_to_completeopt = 1
    let g:ycm_autoclose_preview_window_after_insertion = 1

    " osyo-manga/vim-anzu {{{2
    " anzu setup (plugin that shows number of occurrences when searching)
    " mapping
    nmap n <Plug>(anzu-n-with-echo)
    nmap N <Plug>(anzu-N-with-echo)
    nmap * <Plug>(anzu-star-with-echo)
    nmap # <Plug>(anzu-sharp-with-echo)

    " clear status
    nmap <Esc><Esc> <Plug>(anzu-clear-search-status)

    " statusline
    set statusline=%{anzu#search_status()}

    " Raimondi/delimitMate {{{2
    let delimitMate_expand_cr = 2
    let delimitMate_expand_space = 1
    let delimitMate_jump_expansion = 1
    let delimitMate_balance_matchpairs = 1

    " scrooloose/syntastic {{{2
    let g:syntastic_mode_map = { 'mode': 'active',
                               \ 'active_filetypes': [],
                               \ 'passive_filetypes': ['html'] }

    " rizzatti/dash.vim {{{2
    nmap <Leader>] <Plug>DashSearch
    vmap <Leader>] <Plug>DashSearch

    " majutsushi/tagbar {{{2
    nnoremap <Leader>t :TagbarToggle<CR>

    " tpope/vim-fugitive {{{2
    nnoremap <F7> :Gstatus<CR>

    " kien/rainbow_parentheses.vim {{{2
    au VimEnter * RainbowParenthesesToggle
    au Syntax * RainbowParenthesesLoadRound
    au Syntax * RainbowParenthesesLoadSquare
    au Syntax * RainbowParenthesesLoadBraces

    " 29decibel/vim-stringify {{{2
    map <leader>s :call Stringify()<CR>

    " qstrahl/vim-matchmaker {{{2
    let g:matchmaker_enable_startup = 1

    " sjl/clam.vim {{{2
    nnoremap ! :Clam<space>
    vnoremap ! :ClamVisual<space>

    " othree/javascript-libraries-syntax.vim {{{2
    let g:used_javascript_libs='jquery,underscore'

endif   " s:has_vundle
